modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[21.3.0.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
mandatory=false
versionRange="[18.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=false
versionRange="[11.0.1,)"
ordering="AFTER"
side="BOTH"